### ISSUE TITLE
how to reset PID output value after runing

### ISSUE THREAD

**Issue by gunaone** [br3ttb/Arduino-PID-Library#112]
when i run it, at Output PID 255 and i stop execute it, how i can reset it to 0 again. i try with still running the PID with input far from set poin, its not enough fast to get down to 0 output PID again.

much thans,

**Comment by br3ttb** [comment]
when the pid turns on, it initializes based on the current value of the
output variable. So this should work:
Pid.setmode(manual)
Output=0
Pid.setmode(automatic)

**Comment by gunaone** [comment]
thanks @br3ttb for your replay

so ,
i just execute this code once :
`void reset_PID()
{
  Pid.setmode(manual);
  Output=0;
  Pid.setmode(automatic);
}`

**Comment by br3ttb** [comment]
assuming that "Output" is the name of the variable you linked with the pid
in the constructor, and you want to drop it to 0, then yes.

If you have any error (setpoint!=input) then the output might not be
exactly 0 at startup, because of the pterm contribution.

**Comment by gunaone** [comment]
thanks @br3ttb ,
it's very helpful...
😊😊😊✔
