### ISSUE TITLE
Hard movements on closed loop control with gyro/accelerometer

### ISSUE THREAD

**Issue by nilold** [br3ttb/Arduino-PID-Library#18]
Hi! First at all, thank you very much for your library, its really impressive. 
 I`m using it to make an initially stabilized platform using the MPU-6050 (gyro+ accellerometer) and 2 servos controlling the pitch and the roll. Using two independent PID controllers from our library I could implement it with null error on permanent regime, which is great. 
However,the servos movement are very hard or "steppy", specially noted when moving at intermediary speeds (when I make large abrupt movements, it gets very quickly and straight to the final point, probably because it didn`t had time to make 2 steps). Investigating, I figured out that, although the routine of myPID.Compute() is called at about 100Hz, the output variable is changing it value only at about 10Hz. 
Can I make something to improve it? Is this the maximum computing speed of the compute function?
Thank you very much in advance.

**Comment by prasadghole** [comment]
Let us close this issue and bring down the issue count :+1:
