### ISSUE TITLE
Shouldn't this be +, not -?

### ISSUE THREAD

**Issue by Annonomus-Penguin** [br3ttb/Arduino-PID-Library#28]
**[Here](https://github.com/br3ttb/Arduino-PID-Library/blob/master/PID_v1.cpp#L63),** there is this line of code:

    double output = kp * error + ITerm- kd * dInput;

Shouldn't it be this?:

    double output = kp * error + ITerm + kd * dInput;
    //                                 ^ (switched from -)

Am I reading this wrong here?

**Comment by br3ttb** [comment]
please see: http://brettbeauregard.com/blog/2011/04/improving-the-beginner%E2%80%99s-pid-derivative-kick/
