### ISSUE TITLE
Isn't the D term wrong?

### ISSUE THREAD

**Issue by hoonkai** [br3ttb/Arduino-PID-Library#43]
Hi

Looking at https://github.com/br3ttb/Arduino-PID-Library/blob/master/PID_v1.cpp#L60:

```
     double dInput = (input - lastInput);
 
      /*Compute PID Output*/
      double output = kp * error + ITerm- kd * dInput;
```

Shouldn't `dInput` (D term) be the change in error rather than in input? That is, shouldn't `dInput` be equal to the difference between the current error and the last error?

Thanks

**Comment by qrqiuren** [comment]
Actually they are the same thing.

**Comment by hoonkai** [comment]
Yes, just realised it! :(

**Comment by orgua** [comment]
look at #42 #28 #36
