### ISSUE TITLE
ITerm not properly set when switching modes

### ISSUE THREAD

**Issue by boubougazelle** [br3ttb/Arduino-PID-Library#51]
If you use a proportional pure (ki=0 && kd=0), each time you switch mode, you set an ITerm error equivalent to your output.

It could be prevented using this:
   if(ki < -0.00001 || ki > 0.0001){ // meaning different from 0
    ITerm = *myOutput;
   }
 if(kd < -0.00001 || kd > 0.0001){ // meaning different from 0
    lastInput = *myInput;
   }

**Comment by br3ttb** [comment]
This is the desired behavior. There are times when you want a p-only
controller to work from a baseline other than zero.

If you would like make sure that the pid has a working center of 0, make
output=0 in the calling code before switching from manual to auto.
