### ISSUE TITLE
Input value range?

### ISSUE THREAD

**Issue by aspork42** [br3ttb/Arduino-PID-Library#52]
Is this expecting values from 0-1024? I have an implementation where values are read and linearized and they result from 0-35.

**Comment by br3ttb** [comment]
This library has no input or output span (output limits are a different
thing.) All internal math is done with floats so ranges aren't needed.

The spans thing was required long ago when pids used integers internally.
The specified range would be mapped to some internal, integer, range to
achieve better resolution.

Modern industrial pids keep this convention, and if I ever do an integer
library I may also. But for an arduino floating-point library, I saw zero
benefit.
