### ISSUE TITLE
PID_v1.cpp still references GPLv3 license

### ISSUE THREAD

**Issue by timothyjager** [br3ttb/Arduino-PID-Library#62]
/**********************************************************************************************
 * Arduino PID Library - Version 1.1.1
 * by Brett Beauregard <br3ttb@gmail.com> brettbeauregard.com
 *
 * This Library is licensed under a GPLv3 License
 **********************************************************************************************/

**Comment by br3ttb** [comment]
crap.  the version is also wrong.  didn't think I was going to need a 1.2.1 so quickly, but here we are.
