### ISSUE TITLE
Please add Function to Reset Integral term in PID

### ISSUE THREAD

**Issue by yogesh-s-nanda** [br3ttb/Arduino-PID-Library#87]
In some applications we need to reset the Integral term in the PID function. Please add a function which can be called to reset the Integral term.

**Comment by br3ttb** [comment]
I'd to know your application to know the problem you're trying to solve,
but I'm confident that adding a new function isn't the solution.

with no other information I can point you in two directions:
1: tuning. If your output is winding up in places you don't like, it may be
that your tuning parameters are less than ideal. Also know that you can
call SetTunings to change the values at runtime.

2: reinitialization. If your output is at 100 and you'd like it to
magically jump to 10, you can do this:
Pid.SetMode(manual)
Output=10
Pid.SetMode(automatic)
On the transition from manual to automatic, the pid reads in the current
value of Output and starts adjusting it from there.
