### ISSUE TITLE
PID Output depends on esp8266 board version

### ISSUE THREAD

**Issue by dmikhalsky** [br3ttb/Arduino-PID-Library#95]
I have a code using the PID library that is based on Adafruit Sousvide sketch and works with no issues on Wemos D1 board (esp8266 based)
I get proportional output based on setpoint and actual temperature.
However, when I run **exactly the same code**  on Sonoff device (also esp8266 based) I've got 0 output from PID.Compute

**Comment by EmerickL** [comment]
What was the issue?
